package com.biboheart.dhelloworld.service.model;

import lombok.Data;

@Data
public class HomeInfo {
    private String djid;
    private String jkkh; // isnull(cast(c.vaa82 as varchar(20)),'-') 健康卡号,
    private Double rytz; // isnull(cast(a.vae89 as varchar(20)),'-') 入院体重,
    private Double cstz; // isnull(cast(a.vae90 as varchar(20)),'-') 出生体重 ,
    private Integer jzid; // a.vae01 就诊id,
    //    private String djh; // isnull(vaa66,'-') 登记号,
    private Integer brid; //a.vaa01 病人id ,
    private Integer brxz; // isnull(a.vae04,'-') 病人性质,
    private String ylfkfs; // isnull(cast(a.abj01 as varchar(20)),'-') 医疗付款方式id,
    private String brlb; // a.bdp02 病人类别,
    private String brfb; // a.abc02 病人费别,
    private Integer zry; // a.vae08 再入院,
    private String rybqid; // a.bck01a 入院病区id,
    private String ryksid; // a.bck01b 入院科室id,
    private String ryrq; // a.vae11 入院日期,
    private Integer rysjn; // isnull(datepart(year,a.vae11),'-') 入院时间年,
    private Integer rysjy; //isnull(datepart(month,a.vae11),'-') 入院时间月,
    private Integer rysjr; // isnull(datepart(day,a.vae11),'-') 入院时间日,
    private Integer rysjs; // isnull(datepart(hh,a.vae11),'-') 入院时间时,
    private String rybingqid; // isnull(a.abo01,'-') 入院病情id,
    private String ryfsid; // isnull(a.abr01,'-') 入院方式id,
    private String jzfs; // isnull(a.abt02,'-') 就诊方式,
    private String zymc; // isnull(a.vae15,'-') 转院名称,
    private String rydy; // isnull(a.abz02,'-') 入院待遇,
    private String zymd; // isnull(a.abk02,'-') 住院目的,
    private Integer zycs; // isnull(a.vae19,'-') 住院次数,
    private Integer pb; // isnull(a.vae20,'-') 陪伴,
    private String rycw; // isnull(a.bcq04a,'-') 入院床位,
    private Integer qjcs; // isnull(a.vae33,'-') 抢救次数,
    private Integer hldjid; // isnull(a.aag01,'-') 护理等级id,
    private String zybq; // isnull(a.vae22,'-') 住院病情,
    private String zybqid; // isnull(a.bck01c,'-') 住院病区id,
    private String zyksid; // isnull(a.bck01d,'-') 住院科室id,
    private String zycw; // isnull(a.bcq04b,'-') 住院床位,
    private String cyrq; // a.vae26 出院日期,
    /*isnull(datepart(year,a.vae26),'-') 出院时间年,
    isnull(datepart(month,a.vae26),'-') 出院时间月,
    isnull(datepart(day,a.vae26),'-') 出院时间日,*/
    private String cysjs; // isnull(datepart(hh,a.vae26),'-') 出院时间时,
    //    private String wbyy; // (select top 1 vao15 from  vao2 a where acf01=3  and vaa07=1158 and vao11 = 7) as wbyy , 中毒的外部原因
//    private String h23; // (select a.bak02 from bak1 a left join vao2 b on a.bak01=b.bak01a where acf01=3  and vaa07=1158 and vao11 = 7) h23, 疾病编码
    private Integer zyts; // case when datediff(day,a.vae11,isnull(a.vae26,getdate()))=0 then 1 else datediff(day,a.vae11,isnull(a.vae26,getdate())) end 住院天数,
    //    private String cylxid; // isnull(i.abx01,'-') 出院类型id,
    private Integer qz; // isnull(a.vae29,0) 确诊,
    private Integer xfzl; // a.vae31 新发肿瘤,
    private String qzrq; // a.vae30 确诊日期,
    private Integer cgcs; // a.vae34 成功次数,
    private Integer szbz; // case a.vae35 when 1 then 1 else 2 end 随诊标志,
    private Integer szqx; // a.vae36 随诊期限,
    private String szdw; // case a.vae37 when 'y' then '年' when 'm' then '月' when 'd' then '天' when 'w' then '周' end  随诊单位,
    private Integer sjbz; // case isnull(a.vae38,'-') when 0 then 2 else a.vae38 end  尸检标志,
    //    private Integer abv01; // case a.abv01 when '' then '-' else a.abv01 end,
    private String mzys; // isnull(a.bce03a,'-') 门诊医师,
    private String zrhs; // isnull(a.bce03b,'-') 责任护士,
    private String zyys; // isnull(a.bce03c,'-') 住院医师,
    private String jbbz; // a.vae42 疾病病种,
    private Integer zt; // a.vae44 状态,  0=预约, 1=入院, 2=在院, 3=转科, 4=预出院, 5=结账,6=离院(未结账)9=取消
    private Double je; // a.vae45 金额,
    private String csrq; // c.vaa12 出生日期,
    //    datepart(day,vaa12) 出生天,
//    datepart(month,vaa12) 出生月,
//    datepart(year,vaa12) 出生年,
//    isnull(cast(dbo.getage_day(@vaa07) as varchar(20)),'-') 年龄天,
//    isnull(cast(dbo.getage_month(@vaa07) as varchar(20)),'-') 年龄月 ,
//        dbo.getage_year(@vaa07) 年龄年,
    private Integer nl; // a.vae46 年龄,
    //case a.aau01 when 'y' then '岁' when 'm' then '月' when 'd' then '天' when 'w' then '周' end 年龄单位id,
    private String hyzkid; // isnull(a.ack01,9)  婚姻状况id,
    private String zy; // isnull(a.aat02,'-')  职业,
    private String gj; // isnull(a.acc02,'-') 国籍,
    private String xl; // isnull(a.aay02,'-') 学历,
    private Integer hydwid; // a.baq01 合约单位id,
    private String dwbh; // isnull(c.vaa50,'-') 单位编码,
    private String gzdw; // isnull(a.baq03,' ')工作单位,
    private String dwdh; // isnull(a.vae55,' ') 单位电话,
    private String dwdz; // isnull(c.vaa49,' ')单位地址,
    private String yhb; // t.vct42  邮编号 ,
    //--isnull(c.vaa28,'-') 户口地址,
    private String hkdz; // isnull(t.vct37,'')+isnull(t.vct38,'')+isnull(t.vct39,'')+isnull(t.vct40,'')  户口地址,
    private String hjyb; // isnull(c.vaa29,'-') 户籍邮编,
    private String hjdh; // isnull(c.vaa30,'-') 户籍电话,
    private String csd; // isnull(c.vaa20,' ') 出生地,
    private String csjgs; // isnull(t.vct35,'-') 籍贯省 ,
    private String csjg; //isnull(t.vct36,'-') 籍贯,
    private String xdz; // isnull(a.vae60,'')+isnull(a.vae61,'')+isnull(t.vct41,'')+isnull(a.vae62,'') 现地址,
    private String dh; // isnull(c.vaa34,'-') 电话,
    private String yddh; //isnull(c.vaa35,'-') 移动电话,
    private String dzyx; //isnull(c.vaa36,'-') 电子邮箱,
    private String qtlxfs; // isnull(a.vae66,'-') 其他联系方式,
    private String jhr; // isnull(a.vae67,'-') 监护人,
    private String lxrxm; // isnull(c.vaa40,'-') 联系人姓名,
    private String ybrgx; // isnull(c.vaa41,'-') 与病人关系,
    private String lxrdz; // isnull(c.vaa42,'-') 联系人地址,
    private String lxrdh; // isnull(c.vaa43,'-') 联系人电话,
    private String lxryddh; // isnull(c.vaa43,'-') 联系人移动电话,
    private String zyzllx; // isnull(a.vae73,'-') 中医治疗类别,
    private Integer bxjg; // isnull(a.iaa01, 0) 保险机构,
    //    private String bxh; //isnull(x.iak05,'-') 保险号,
    private Integer sq; // isnull(a.uaa01,'-') 社区id,
    private Integer sh; // a.vae76 审核,
    private String shr; // a.bce03d 审核人,
    private String shrq; // a.vae78 审核日期,
    private Integer scbz; //a.vae79 上传标志,
    private Integer zcbz; //a.vae80 转出标志,
    private String djr; // a.bce03e 登记人,
    private String zbsj; // a.vae82 制表时间,
    private Integer dazt; //a.vae84 档案状态,
    private String remark; //a.vae83 备注,
    private String cdsj; //a.vae85 存档时间,
    private String bs; // b.vam02 病室,
    private String cyks; //b.vam03 出院病室,
    private Integer ywzk; // b.vam04 有无转科,
    private String blfl; // b.vam05 病例分型,
    private String zgzdyj; //b.vam07 最高诊断依据,
    /*private Integer hbsag; // isnull(b.vam08,0) hbsag,
    private Integer hcv_ab; // isnull(b.vam09,0) hcv_ab,
    private Integer hiv_ab; // isnull(b.vam10,0) hiv_ab,*/
    private Integer ryqwyzz; // b.vam06 入院前经外院诊治,
    private Integer yn; //b.vam11 疑难,
    private Integer wz; //b.vam12 危重,
    private Integer jz; //b.vam13 急症,
    private String bz; // b.vam14 辨证,
    private String zf; // b.vam15 治法,
    private String fy; //b.vam16 方药,
    private String qjff; //b.vam17 抢救方法,
    private String zzzy; // b.vam18 自制中药,
    private Integer zymzyzy; // isnull(b.vam19,1)  中医门诊与住院,
    private Integer mzycy; // isnull(b.vam21,0)  门诊与出院,
    private Integer ryycy; // isnull(b.vam22,0)  入院与出院,
    private Integer zyryycy; //isnull(b.vam20,1)  中医入院与出院,
    private Integer sqysh; // isnull(b.vam23,0)  术前与术后,
    private Integer lcybl; // isnull(b.vam24,0)  临床与病理,
    private Integer fsybl; // isnull(b.vam25,0)  放射与病理,
    private String kzr; // isnull(b.vam26,'-') 科主任,
    private String zrys; // isnull(b.vam27,'-') 主任医师,
    private String jxys; // isnull(b.vam28,'-') 进修医师,
    private String yjssxys;// isnull(b.vam29,'-') 研究生实习医师,
    private String sxys; // isnull(b.vam30,'-') 实习医师,
    private String fhcd; //isnull(b.vam32,'-') 分化程度,
    private String zzys; // isnull(b.vam31,'-') 主治医师,
    private String bazl; // isnull(b.vam33,'-') 病案质量,
    private String zkys; // isnull(b.vam34,'-') 质控医师,
    private String zkhs; // isnull(b.vam35,'-') 质控护士,
    private String zkrq; // case when cast (b.vam36 as varchar(20)) is null then '-' else  convert(varchar(10),b.vam36,120) end as 质控日期,
    private Integer zdss; // b.vam37 中度烧伤,
    private String swyy; // b.vam38 死亡原因,
    private String swsj; // b.vam39 死亡时间,
    private Integer slss; // isnull(b.vam40,2) 首例手术,
    private Integer slzz; // isnull(b.vam41,2) 首例治疗,
    private Integer sljc; /// isnull(b.vam42,2) 首例检查,
    private Integer slzd; // isnull(b.vam43,2) 首例诊断,
    private Integer sz; // case isnull(b.vam44,2) when 1 then 1 when 2 then 2 else 2 end 随诊,
    private Integer sjbl; // case isnull(b.vam45,2) when 1 then 1 when 2 then 2 else 2 end 示教病例,
    private Integer kybl; // isnull(b.vam46,2) 科研病例,
    private Integer sxqjxjc; // isnull(b.vam47,'') 输血前9项检查,
    private Integer sxfy; // case isnull(b.vam48,2) when 1 then 1 when 2 then 2 else 2 end 输血反应,
    private Integer syfy; // isnull(b.vam49,2) 输液反应,
    private Double hxb; //b.vam50 红细胞,
    private Double xxb; //b.vam51 血小板,
    private Double xj; //b.vam52 血浆,
    private Double qx; //b.vam53 全血,
    private String qtsx; // b.vam54 其他输血,
    private Integer yjhz; // isnull(b.vam55,'0') 院际会诊,
    private Integer ychzcs; //isnull(b.vam56,'0') 远程会诊次数,
    private Integer tjhlxs; // b.vam57 特级护理小时,
    private Integer yjhl; // b.vam58 ⅰ级护理,
    private Integer ejhl; // b.vam59 ⅱ级护理,
    private Integer sjhl; // b.vam60 ⅲ级护理,
    private Integer zzjh; // b.vam61 重症监护,
    private Integer tshl; // b.vam62 特殊护理,
    private Integer yxglzbqxjc; // b.vam63 医学感染作病源学检查,
    private Integer sykss; // isnull(b.vam64,0) 使用抗生素,
    private Integer dbz; // isnull(b.vam65,0) 单病种,
    private Integer bfbz; // isnull(b.vam66,0) 部分病种,
    private Double zyzfy; // b.vam67 住院总费用,
    private Double zfje; // b.vam67 自付金额,
    private String bmy; // b.vam68 编码员,
    private String bmrq; // b.vam69 编码日期,
    private String cjz; // b.vam70 创建者,
    private String cjrq; // b.vam71 创建日期,
    //    private String zyks; // q.bck03 住院科室,
    private Integer symd; // b.vam72 使用目的,
    private Integer syfa; // b.vam73 使用方案,
    private String kss; // b.vam74 抗生素,
    private String sysj; // b.vam75 使用时间,
    private String zyh; // c.vaa04 住院号,
    private String xm; // c.vaa05 姓名,
    private Integer xxid; // case isnull(c.abl01,9) when 1 then 1 when 2 then 2 when 3 then 3 when 4 then 4 when 5 then 5 when 6 then 6 else 6 end 血型id,
    private Integer rhxx; // case isnull(c.vaa78,3) when 1 then 1 when 2 then 2 when 4 then 4  else 3 end  rh血型,
    private String sfzh; // case vaa15 when '' then '-' when null then '-' else vaa15 end  身份证号,
    private String qtzj; // isnull(c.vaa16,'-') 其他证件,
    private String xbid; // isnull(c.abw01,'-') 性别id,
    private String mz; // isnull(c.abq02,'-') 民族,
    //    private String ryks; // isnull(d.bck03,'-') 入院科室,
    private String ss; // isnull(c.vaa31,'-') 省市,
    private String xlc; // isnull(c.vaa38,'-') 学历,
    private String gzdwa; // isnull(c.vaa47,'') 工作单位,
    private String dwdha; // isnull(c.vaa48,'') 单位电话,
    private String dwdza; // isnull(c.vaa49,'') 单位地址,
    private String dwyb; // isnull(c.vaa50,'-') 单位邮编,
    private String dwkhh; // isnull(c.vaa51,'-') 单位开户行,
    private String dwyhzh; // isnull(c.vaa52,'-') 单位银行帐号,
    private String hkdza; // isnull(c.vaa28,'-') 户口地址,
    private String hkxs; // isnull(c.vaa32,'-') 县市,
    private String dz; // isnull(c.vaa33,'-') 地址,
    //    private Integer hbz; // isnull(b.vam76,2) 合并症,
//    private Integer bfz; // isnull(b.vam77,2) 并发症,
//    private Integer vao01a; // e.vao01 vao01a,
//    private Integer bak01a; // e.bak01a bak01a,
//    private String bak05a; // f.bak05,
//    private String mzzd; // e.vao15 门诊诊断,
//    private String jbbm; // f.bak02 疾病编码,
//    private Integer vao01b; // g.vao01 vao01b,
//    private Integer bak01b; // g.bak01a bak01b,
//    private String bak05b; // h.bak05,
//    private String ryzd; // isnull(g.vao15,'-') 入院诊断,
//    private Integer vao01c; // i.vao01 vao01c,
//    private Integer bak01c; // i.bak01a bak01c,
//    private String bak05c; // j.bak05,
//    private String cyzd; // i.vao15 出院诊断,
//    private Integer vao24; //i.vao24, 入院病情
//    private String abx01c; // i.abx01 abx01c,
//    private String icd10; // j.bak02 icd10,
//    private Integer vao01d; //k.vao01 vao01d,
//    private Integer bak01d; // l.bak02 bak01d,
//    private String bak05d; // l.bak05,
//    private String blzd; // isnull(k.vao15,'-') 病理诊断,
//    private String mzzyzd; // m.vao15 门诊中医诊断,
//    private Integer vao01f; // o.vao01 vao01f,
//    private Integer bak01f; // o.bak01a bak01f,
//    private String bak05f; //p.bak05,
//    private String cyzyzd; //o.vao15 出院中医诊断,
//    private String yyglmc; // case when r.vao15>'' then r.vao15 else '-' end 医院感染名称,
    private String ywgm; // case isnull(van1.bbx05,'1')when '1' then '1' else '2'end 有无过敏,
    private String gmyw; // isnull(van1.bbx05,'-') 过敏药物,
    private String lyfs; // isnull(cast(mm.rownr as varchar(20)),'-') 离院方式,
    private Integer sfy31tzryjh; // case isnull(b.vam88,'1') when '1' then '1' else '2' end 是否有31天再入院计划,
    private String njsyljgmc; // isnull(a.vae92,'-') 拟接收医疗机构名称,
    private String zrymd; // isnull(b.vam88,'-') 再入院目的,
    private String rnssryq; //isnull(b.vam89,'-') 颅脑损伤入院前,
    private String rnssryh; // isnull(b.vam90,'-') 颅脑损伤入院后,
    private String lclj; // b.vam96 临床路径 ,
    private String bah; //a.vaa08 病案号,
    private String blh; // b.vam82 病理号
}
