server:
  port: 8080
#  session:
#    timeout: 30 # Session timeout in seconds.
spring:
#  profiles:
#    active: dev
#  session:
#    store-type: redis
#    redis:
#      flush-mode: # Sessions flush mode.
#      namespace: # Namespace for keys used to store sessions.
  output:
    ansi:
      enabled: DETECT
  http:
    encoding:
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: 500MB
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bh_springbootdemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
#    username: root
#    password: root
#  jpa:
#    database: MYSQL
#    show-sql: false
#    hibernate:
#      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        format_sql: false
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: test
#    password: test
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 5
    # redis服务器地址（默认为localhost）
    host: localhost
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password: 
    # redis连接超时时间（单位为毫秒）
    timeout: 3600000
    # redis连接池配置
    jedis:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: -1
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 200
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1
# LOGGING
logging:
  level:
    root: info
