server:
  port: 8080
spring:
  profiles:
    active: dev
  resources:
    static-locations: file:/usr/biboheart/bootdemos/dhelloworld/static, classpath:/static/
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown
custom:
  name: bhhello-app
