server:
  port: 9000
  dataPath: E:/usr/biboheart/bootdemos/dwechat
spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev
  output:
    ansi:
      enabled: detect
  http:
    encoding:
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: 500MB
# LOGGING
logging:
  level:
    root: info
