server:
  port: 8080
security:
  oauth2:
    client:
      client-id: client_1
      client-secret: 123456
      access-token-uri: http://jhhis.tsyljt.com/platformauth/oauth/token
      user-authorization-uri: http://jhhis.tsyljt.com/platformauth/oauth/authorize
      grant-type: client_credentials
    resource:
      user-info-uri: http://jhhis.tsyljt.com/platformauth/platformapi/auth/user/info
      prefer-token-info: false
spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: detect
  http:
    encoding:
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: 500MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.2.127:3306/eber_ehis_test_dev?serverTimezone=UTC&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
#    username: root
#    password: dbadmin@21ber.com
#   金华
    url: jdbc:mysql://183.129.254.230:13983/bh_test?serverTimezone=UTC&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: jhts
    password: jhts@mysql
#    url: jdbc:mysql://183.129.254.230:13833/eber_ehis?serverTimezone=UTC&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
#    username: root
#    password: jxdx@mysql
  jpa:
    show-sql: false
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown
