server:
  port: 8080
spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: detect
  http:
    encoding:
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: 500MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://120.26.195.9:3812/bh_demos_database?serverTimezone=UTC&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    url: jdbc:mysql://192.168.2.127:3306/bh_demos_database?serverTimezone=UTC&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: dbadmin@21ber.com
  jpa:
    show-sql: true
    database: default
#    database-platform: org.hibernate.dialect.MySQL5Dialect
    database-platform: com.biboheart.ditems.jpa.EberMysql5Dialect
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: false
